apiVersion: v1
kind: Namespace
metadata:
  name: curl
  labels:
    istio-injection: enabled
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  namespace: curl
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: curl
spec:
  serviceAccountName: curl
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do curl -v http://app1.app1.svc.cluster.local; sleep 3; done
    image: nicolaka/netshoot
    name: curl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
